version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: fastapi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/mydb
    volumes:
      - .:/app
    ports:
      - "80:80"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

